#!/usr/bin/env python3
"""Refresh the volatile figures in README.md from public/data (run as the last
step of the weekly rebuild). Rewrites only:
  - the AUTO-HIGHLIGHTS block (the headline table + its "last refresh" line)
  - the activity count and end month in the intro sentence
Everything else in the README is hand-authored and left untouched.
"""
import csv, os, re, datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = os.environ.get("STRAVA_OUTPUT", str(ROOT / "public" / "data"))
README = ROOT / "README.md"
FOOT = {"Walk", "Run", "TrailRun", "Hike"}
MONTHS = ["", "January", "February", "March", "April", "May", "June",
          "July", "August", "September", "October", "November", "December"]


def rows(name):
    with open(os.path.join(OUT, name)) as f:
        return list(csv.DictReader(f))


def fnum(x):
    try:
        return float(str(x).replace(",", "").strip())
    except Exception:
        return 0.0


def commas(n):
    return f"{int(round(n)):,}"


def long_date(iso):
    d = datetime.date.fromisoformat(iso[:10])
    return f"{d.day} {MONTHS[d.month]} {d.year}"


# ---- gather figures ----
life = {r["metric"]: r["value"] for r in rows("lifetime_totals.csv")}
streaks = {r["metric"]: r["value"] for r in rows("streaks.csv")}
meta = {r["key"]: r["value"] for r in rows("meta.csv")}
sb = rows("sport_breakdown.csv")
countries = rows("countries.csv")
regions = rows("tanzania_regions.csv")
acts = rows("activities.csv")

activities = int(fnum(life["Total Activities"]))
foot_km = int(fnum(life["Total Km"]))
foot_hours = round(sum(fnum(r["moving_time_h"]) for r in sb if r["sport"] in FOOT))
foot_elev = int(fnum(life["Total Elevation (M)"]))
everest = foot_elev / 8849
kudos = int(fnum(life["Total Kudos"]))
_ds = streaks.get("Longest consecutive-day streak") or str(life.get("Longest Streak (Days)", "0"))
day_streak = int(re.search(r"\d+", _ds).group()) if re.search(r"\d+", _ds) else 0
country_count = sum(1 for r in countries if r["country"] and "Indoor" not in r["country"])
region_count = len(regions)
end_iso = meta["coverage_end"]
end_month = f"{MONTHS[int(end_iso[5:7])]} {end_iso[:4]}"

# week streak: consecutive ISO weeks (Mon-anchored) with >=1 activity, ending at the last week
weeks = set()
for r in acts:
    d = datetime.date.fromisoformat(r["date"][:10])
    weeks.add(d - datetime.timedelta(days=d.weekday()))
week_streak = 0
if weeks:
    cur = max(weeks)
    while cur in weeks:
        week_streak += 1
        cur -= datetime.timedelta(days=7)
week_years = round(week_streak / 52)

# ---- build the highlights block ----
block = f"""<!-- AUTO-HIGHLIGHTS:START (regenerated by scripts/update_readme.py on each refresh; do not edit by hand) -->
At the last refresh ({long_date(end_iso)}) the record covered:

| Metric | Value |
| --- | --- |
| Activities | {activities:,} |
| Distance on foot | {foot_km:,} km |
| Moving time on foot | {foot_hours:,} hours |
| Elevation gained on foot | {foot_elev:,} m (about {everest:.1f} times Everest) |
| Kudos received | {kudos:,} |
| Longest active streak | {day_streak} days, still going |
| Longest week streak | {week_streak} weeks (about {week_years} years), still going |
| Countries | {country_count} |
| Tanzanian regions | {region_count} |
<!-- AUTO-HIGHLIGHTS:END -->"""

text = README.read_text(encoding="utf-8")
new = re.sub(r"<!-- AUTO-HIGHLIGHTS:START.*?<!-- AUTO-HIGHLIGHTS:END -->",
             block, text, count=1, flags=re.DOTALL)

# intro sentence: "**N activities** logged between August 2019 and <Month Year>"
new = re.sub(r"\*\*[\d,]+ activities\*\* logged between August 2019 and [A-Za-z]+ \d{4}",
             f"**{activities:,} activities** logged between August 2019 and {end_month}",
             new, count=1)

if new != text:
    README.write_text(new, encoding="utf-8")
    print(f"README.md updated: {activities:,} activities, {foot_km:,} km, "
          f"{day_streak}d / {week_streak}wk streak, {country_count} countries, "
          f"{region_count} regions, through {long_date(end_iso)}")
else:
    print("README.md already current (no change)")
